<a href="https://colab.research.google.com/github/Vikky6789/pytorch_all/blob/master/Learning_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_torch=my_torch.reshape(2,5)

In [5]:
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
my_torch2=torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch2=my_torch2.reshape(2,-1)

In [9]:
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch2=my_torch2.reshape(-1,5)

In [11]:
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch3=torch.arange(10)
my_torch4=my_torch3.view(2,-1)

In [13]:
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
my_torch4[1]=1;

In [17]:
my_torch4

tensor([[0, 1, 2, 3, 4],
        [1, 1, 1, 1, 1]])

In [18]:
my_torch5=torch.arange(10)
my_torch5[7]

tensor(7)

In [19]:
my_torch6=torch.arange(10)
my_torch6=my_torch6.reshape(5,2)
my_torch6[:,1]

tensor([1, 3, 5, 7, 9])

In [20]:
my_torch6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])